### ISSUE TITLE
XNAT fails to upload output files from FastSurfer analysis

### ISSUE THREAD

**Issue by milanmlft** [UCL-MIRSG/xnat-aws#74]
The FastSurfer analysis runs successfully now but there is still an issue with the output files. For some reason, XNAT fails to upload them (see screenshot), though they are present in the correct path (manually confirmed by `ssh`ing into the EC2 instance).

![image](https://github.com/UCL-MIRSG/xnat-aws/assets/38256462/7e62d42a-b389-45b3-99b6-2ebbdfd04676)

**Comment by milanmlft** [comment]
@davecash75, just continuing [our conversation](https://github.com/HealthBioscienceIDEAS/IDEAS/issues/19#issuecomment-1686676552) here to keep track.

Would you be able to deploy the `xnat-aws` infrastructure yourself and run the FastSurfer analysis to reproduce the error?

Steps needed:

1. Generate credentials
```
cd credentials
terraform init
terraform apply
```

2. Deploy infrastructure
```
cd ../provision
terraform init
terraform apply
```

3. Instal XNAT
```
cd ../configure
./install_xnat.sh
```

4. Set up example project
This can take quite some time to upload all data, but I would suggest just killing the script after the first dataset has uploaded

```
# still from configure/
./setup_xnat_project.sh
```

5. Run FastSurfer analysis
	1. Run `dcm2niix` command on a T1 scan
	2. Run `Converts NIFTI to 256 conformed MGZ file`
	3. Run `Run FastSurfer pipeline on a conformed T1 MGZ - CPU`
	Note that the FastSurfer pipeline can take about 2 hours

**Comment by p-j-smith** [comment]
alternatively @davecash75 , do you have the Dockerfile (or image) that was used in the workshop last year? The [only FastSurger image on the Health Biosciences Ideas docker hub](https://hub.docker.com/layers/healthbioscienceideas/fastsurfer/gpu/images/sha256-8110b0a8e4ae31a96ca3993ffee039200bb5f8aa53287ec575b271e884f00608?context=explore) had the incorrect tag (`gpu` rather than `gpu-xnat`) and was actually running pydeface rather than FastSurfer. So @milanmlft built [a new image](https://hub.docker.com/layers/healthbioscienceideas/fastsurfer/gpu-xnat/images/sha256-1129074decb4875f76c541af6111b72711d8063a5c43a9d6c1248289d20d6899?context=explore) based on the latest fastsurfer image but now we're having the issue that the output fails to upload after the analysis is finished

**Comment by davecash75** [comment]
Apologies - I can't find it on my laptop. @HChughtai  - might this image/container still be on the machine we ran it on last year if it hasn't been rebuilt?
I'll keep digging to see if I can find anything. It might be on an old laptop.

**Comment by HChughtai** [comment]
Afraid not - that machine has been rebuilt since. It looks like the container is running and the expected outputs produced, so I doubt it's the image itself. More likely the command wrapper, file permissions somewhere or a timeout somewhere

**Comment by milanmlft** [comment]
Seems it was a memory issue after all... I used a larger EC2 instance with more RAM and configured `tomcat` and the Docker image to have higher max. memory settings, and now it works!

**Comment by milanmlft** [comment]
Feel free to try it out! I think this particular issue is solved now, so no need to dig further into it. But in any case it would be good to get some feedback on our setup in general. No rush though! 🙂
